name: renovate_ranger
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter   
  #UI
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  fl_chart: ^0.69.0
  flutter_localization: ^0.2.2
  flutter_launcher_icons: ^0.14.1
  #Logic
  in_app_review: ^2.0.9
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  #database
  hive: 2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_foreground: "assets/launch/Icon-App.jpg"
  image_path: "assets/launch/Icon-App.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/launch/Icon-App.jpg"

flutter:

  uses-material-design: true


  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/toolsfiller.x2.png
    - assets/images/contactsfiller.x2.png
    - assets/images/projectsfiller.x2.png
    - assets/images/advice_image.jpg

    #icons
    - assets/icons/Notes/Document Add.svg
    - assets/icons/Arrows/Round Arrow Left.svg
    - assets/icons/Arrows/Round Arrow Right.svg
    #Settings screen Icons
    - assets/icons/Hands/Hand Stars.svg
    - assets/icons/School/Notebook Bookmark.svg
    - assets/icons/Security/Lock Unlocked.svg
    #Appbar
    - assets/icons/Essentional, UI/Sort.svg
    #add project screen
    - assets/icons/download/Download Minimalistic.svg
    #contacts screen
    - assets/icons/Call/Phone Rounded.svg
    - assets/icons/email/Property 1=Linear, Property 2=Messages, Conversation, Property 3=Letter.svg
    - assets/icons/Essentional, UI/Menu Dots.svg
    #add tools
    - assets/icons/hammer/hammer=off.svg
    - assets/icons/nail/nail=off.svg
    - assets/icons/hammer/hammer=on.svg
    - assets/icons/nail/nail=on.svg
    #tools screen
    - assets/icons/Essentional, UI/Add Circle.svg
    - assets/icons/Essentional, UI/Minus Circle.svg

    #Fonts
  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/AlegreyaSans-Black.ttf
        - asset: assets/fonts/AlegreyaSans-Bold.ttf