name: renovate_ranger
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: ^1.0.8

  #smt
  flutter_screenutil: ^5.9.3

  #Logic
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  assets:
    - lib/assets/images/onboarding1.png
    - lib/assets/images/onboarding2.png
    - lib/assets/images/onboarding3.png
